"""add_composite_index_photos

Revision ID: 070dade6a602
Revises: 652a0c987696
Create Date: 2026-02-07 14:11:53.649345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070dade6a602'
down_revision: Union[str, Sequence[str], None] = '652a0c987696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_photos_type_ad', 'ad_photos', ['ad_type', 'ad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photos_type_ad', table_name='ad_photos')
    # ### end Alembic commands ###
