"""add_channel_message_id

Revision ID: 489f2a89e0c7
Revises: 070dade6a602
Create Date: 2026-02-07 14:24:56.248745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489f2a89e0c7'
down_revision: Union[str, Sequence[str], None] = '070dade6a602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_ads', sa.Column('channel_message_id', sa.Integer(), nullable=True))
    op.add_column('plate_ads', sa.Column('channel_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plate_ads', 'channel_message_id')
    op.drop_column('car_ads', 'channel_message_id')
    # ### end Alembic commands ###
